### PR TITLE
Added 'activate' function and the possibility to decide if display the button on the map

### PR DESCRIPTION
**Pull request by rikyDeg**
Hi, I added a new function `activate`, when it's called starts the process for drawing the polygon.
The possibility to show or hide the button can be done through a new parameter on the constructor. 
The default behavior is the same as the previous version.

### CODE REVIEW

**Comment by keul** [comment]
Hi @rikyDeg,

thanks for the contribution but I did not understand how a user is supposed to use this feature.

Can you provide an example code?

**Comment by rikyDeg** [comment]
Hi, it can be useful when you need to implement an external toolbox for managing the polygon on the map.
On creating the map instance, setting the button not visible on the map, through a custom external toolbox is possible to activate/deactivate the polygon drawing action and manage the polygon according to the existing callbacks.

**Comment by keul** [comment]
@rikyDeg OK now I got it.

I agree on adding the [activate method](https://github.com/bopen/leaflet-area-selection/pull/5/files#diff-53aa5b852a2ae4fc1256622d467574e40ceea689796466f62dfa9cd6c0d66e34R215) which I think will be useful for your usecase.

But I would not add complexity for hiding the button using JavaScript. It's adding many "ifs" statement, while we can keep the code simple. If an integrator wants to hide the button, he just need a single line of CSS.

What you think? If you can remove the `showButton` stuff I'll be happy to merge

**Comment by rikyDeg** [comment]
Hi @keul, I agree with you, in my last commit I removed the `showButton` stuff!

**Pull request merged**
